import type { Rating, WeatherKind } from '../EdgeBrake/types'
import type { CharacterCategory } from '../EdgeBrake/characters'

export const game = {
  title: 'EDGE BRAKE',
  subtitle: 'Hold for power. Release for the edge.',
  eyebrow: 'SOUTH POLE BRAKE CLUB',
  hold: 'HOLD',
  holdToCharge: 'HOLD TO CHARGE',
  releaseToLaunch: 'RELEASE TO LAUNCH',
  level: 'LEVEL',
  score: 'SCORE',
  coins: 'COINS',
  runCoins: 'RUN COINS',
  edge: 'ON THE EDGE!',
  great: 'BEAUTIFUL!',
  safe: 'SAFE STOP',
  early: 'NOT ENOUGH POWER',
  earlyFailTitle: 'NOT ENOUGH POWER',
  earlyFailReason: 'The hold was too short',
  earlyFailRule: 'CHARGE A LITTLE LONGER',
  roundScore: 'ROUND SCORE',
  nextCharacter: 'NEXT CREW',
  retryRound: 'RETRY LEVEL',
  nextCrew: 'UP NEXT',
  retryCrew: 'TRY AGAIN WITH',
  distance: (n: number) => `${n}px TO EDGE`,
  fallen: 'TOO FAR!',
  resultTitle: 'ICE INCIDENT REPORT',
  passed: 'LEVELS CLEARED',
  bestDistance: 'CLOSEST STOP',
  bestCombo: 'BEST EDGE STREAK',
  bestScore: 'BEST SCORE',
  again: 'NEW EXPEDITION',
  home: 'BACK TO COVER',
  soundOn: 'Turn sound on',
  soundOff: 'Turn sound off',
  expedition: 'EXPEDITION CREW',
  expeditionNote: 'Different weight, different speed',
  collection: (n: number) => `${n}/52 COLLECTED`,
  unlocked: 'NEW CREW UNLOCKED',
  weight: 'WEIGHT',
  speed: 'SPEED',
  inUse: 'IN USE',
  owned: 'SELECT',
  buy: (n: number) => `${n} COINS`,
  notEnough: (n: number) => `${n} COINS SHORT`,
  close: 'Close expedition crew',
  cliffDistance: 'TO CLIFF',
  weatherForecast: 'CONDITIONS',
  weather: {
    clear: 'CLEAR',
    snow: 'SNOW',
    fog: 'FOG',
    blizzard: 'BLIZZARD',
  } satisfies Record<WeatherKind, string>,
  weatherEffect: {
    clear: 'STABLE ICE. HOLD AS USUAL.',
    snow: 'FRESH SNOW. RELEASE EARLIER.',
    fog: 'WET ICE. HOLD A LITTLE LESS.',
    blizzard: 'CROSSWIND. KEEP THE HOLD STEADY.',
  } satisfies Record<WeatherKind, string>,
  weatherChange: {
    clear: 'NO DRAG CHANGE',
    snow: 'DRAG +5%',
    fog: 'DRAG −6%',
    blizzard: 'DRAG +3%',
  } satisfies Record<WeatherKind, string>,
  category: {
    people: 'PEOPLE',
    archetypes: 'ARCHETYPES',
    monsters: 'MONSTERS',
    office: 'OFFICE',
    villains: 'ELITE',
    mechs: 'MECH',
    mythic: 'MYTHIC',
    animals: 'ANIMALS',
  } satisfies Record<CharacterCategory, string>,
}

export const ratingCopy: Record<Rating, string> = {
  edge: game.edge,
  great: game.great,
  safe: game.safe,
  early: game.early,
}

export const desk = {
  contracts: 'CONTRACTS',
  workshop: 'WORKSHOP',
  thisIce: 'THIS ICE',
  howTo: 'HOW TO PLAY',
  camp: 'CAMP',
  best: 'BEST',
  clears: 'CLEARED THIS RUN',
  passRule: 'Pass within 320px of the cliff. The edge band is 0–10px.',
  shopLocked: 'Gear can be bought between rounds.',
  stock: 'Stock sled. No workshop gear yet.',
  maxed: 'MAXED',
  buy: 'BUY',
  needCoins: (n: number) => `NEED ${n}`,
  needCamp: (n: number) => `CAMP ${n}`,
  campRule: 'Camp rank must reach the next gear rank.',
  music: 'Music: Black Diamond by Joth (CC0)',
  tutorialSkip: 'SKIP',
  tutorialNext: 'NEXT',
  tutorialStart: 'PLAY',
  tutorialKicker: 'FIRST RUN',
  steps: [
    {
      title: 'Hold, then release',
      body: 'Hold Space, Enter, or the mouse. The bar fills over 1.6 seconds. Release to launch the crew down the ice.',
    },
    {
      title: 'Stop on the edge',
      body: 'The gold window on the charge bar is a rough aim. Release inside it. Closer stops pay more. Past 320px is too short. Over the cliff ends the expedition.',
    },
    {
      title: 'The camp remembers',
      body: 'Cliff Sense tightens the gold window. Springs shift it earlier. Studs make the same hold stop shorter. Camp rank unlocks the next gear rank and pays coins.',
    },
  ],
}
